import type { Metadata } from "next";
import {Montserrat} from "next/font/google"

import "./globals.css";
import Navbar from "./components/Navbar";

const montserrat = Montserrat({
  subsets:["latin"],
  weight:['100','200','300','400' ,'500','600','700'],
  display:"swap"

})



export const metadata: Metadata = {
  title: "Frontend Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
